### ISSUE TITLE
Link master-webmap

### ISSUE THREAD

**Issue by dhunink** [EsriEduNL/veldwerk2.0#14]
We need to find a way to link the duplicate maps (that are assigned to groups) to the master-webmapp.
By doing so we can eliminate those maps from the listing in the 'select webmap' UI view and show all the groups that have a map that's based on that mastermap after a mastermap is selected.

**Comment by mvanhulzen** [comment]
By using a tag when creating the webmap and filtering on that tag in de list.

**Comment by dhunink** [comment]
Added. Also added labels referring to the map ID in the groups
