### ISSUE TITLE
function createStudentUser results in error

### ISSUE THREAD

**Issue by dhunink** [EsriEduNL/veldwerk2.0#24]
{"error":{"code":400,"messageCode":"GWM_0002","message":"Invalid URL","details":[]}}

**Comment by mvanhulzen** [comment]
possible solution: change portalurl to xxx.maps.arcgis.com instead of arcgis.com for this call

**Comment by dhunink** [comment]
Fixed by replacing with the following url
    var requestUrl = portalUrl + "/sharing/rest/portals/" + portal.id + "/users";
