### ISSUE TITLE
Count unique, not rows

### ISSUE THREAD

**Issue by dhunink** [EsriEduNL/veldwerk2.0#56]
When reading and processing a drag-and-drop Excel, the script looks to the column groups and counts the number of rows. This should be altered to counting the unique number of rows. For example, in the screenshot below, their actually are only 2 groups. So the script would only count Klas1 and Klas2.
![schermafbeelding 2015-03-29 om 14 40 44](https://cloud.githubusercontent.com/assets/2500356/6885466/d1b176b4-d621-11e4-96b4-d04a171de7c1.png)

**Comment by mulderniels** [comment]
Fixed:)

**Comment by mulderniels** [comment]
btw. i removed the counting (2 van 3) because it is hard to decide what to count? Unique groups in table? Success only? But what if you have an error and only count success?
